### ISSUE TITLE
This is not the net-ssh-telnet you're looking for

### ISSUE THREAD

**Issue by jasonkarns** [seandilda/net-ssh-telnet#6]
update readme with disclaimer

**Comment by jasonkarns** [comment]
Would the original authors (or at least contributors and publishers of the gem) @mdkent @candlerb care to take ownership of this repo? Now that the ruby forge is no more?

**Comment by candlerb** [comment]
I do very little ruby these days and would be happy to transfer gem ownership.

I see there is a command `gem owner` - I need to know the E-mail of the new owner.

**Comment by jasonkarns** [comment]
@candlerb Thanks for responding. Actually, I was hoping to transfer this repo _to you_. :) I don't do too much ruby these days either, especially not anything with this gem. I'm nearly 5 years removed from even looking at this thing.

**Comment by lumean** [comment]
Hi Guys, I'd be willing to take the ownership, since we use this gem in our company quite a lot for automation tasks. 
There's also that other gem which seems to be a fork, but is not listed in the forks: https://github.com/duke-automation/net-ssh-telnet2 , they didn't change the class name so it doesn't make sense to have both installed (or need bundler). If you agree I would then merge their changes into this repo and push a new gem, maybe also with some of the forks merged.

**Comment by seandilda** [comment]
As the owner of https://github.com/duke-automation/net-ssh-telnet2  (https://rubygems.org/gems/net-ssh-telnet2), I'd be happy to take over the gem, merge my changes for net-ssh-telnet2 into it and kill my fork.   The fork only exists because I had some fixes and the original gem didn't seem to be maintained.

**Comment by jasonkarns** [comment]
@seandilda to be clear, this git repo is a github clone/fork of the original rubyforge repo, which corresponds to the net-ssh-telnet gem on rubygems. Despite this being the _source_ for the gem on rubygems, I am not the owner of the gem nor can i transfer ownership of the gem (on rubygems). I simply forked the rubyforge repo over to github.

I would love to transfer ownership of this repo to a maintainer. However, I would prefer this repo be transferred to someone that also owns the gem on rubygems. Presently, that is only @mdkent and @candlerb

**Comment by candlerb** [comment]
If I have rights to transfer the ownership of the gem, I would be happy to do so.  Just point me at the instructions for what I need to do.  It is years since I did any gem publishing.

**Comment by jasonkarns** [comment]
@candlerb looks like you can do it through the `gem owner` command: http://guides.rubygems.org/command-reference/#gem-owner

seems that @seandilda and @lumean are both interested? appear to be owners of the same duke-automation fork?

**Comment by seandilda** [comment]
@jasonkarns sorry, I realized that, I meant the previous comment for @candlerb.

@candlerb, I'd be happy to take over gem ownership if you want to pass it on.  @lumean has submitted pull requests to my repo, but isn't one of the owners of that repo.

**Comment by lumean** [comment]
I'm perfectly fine if @seandilda would take over the gem. I just once did a small contribution to the duke-automation fork but am not an owner. My main motivation was just to get this maintained again.

**Comment by jasonkarns** [comment]
@seandilda should I transfer the gem to you directly or the @duke-automation org?

**Comment by seandilda** [comment]
@jasonkarns thanks for transferring the repo.  Once @candlerb adds me as an owner to the gem, I'll get all the appropriate links cleaned up.

**Comment by candlerb** [comment]
Added owner, appears to have been successful - please test.

**Comment by seandilda** [comment]
Thanks for everyone's help with getting the gem transferred over.

I've updated the gem with the fixes from my repo - this caused all the links on rubygems.org to be updated to the new official repo:  https://github.com/duke-automation/net-ssh-telnet

Since this is not the official repo, I'm going to delete this repo in a few minutes.  If you wish to have a fork for any reason, please do so off of https://github.com/duke-automation/net-ssh-telnet
